import { type VtmDraft } from "../types";
export const emptyVtmDraft = (): VtmDraft => ({
  system: "vtm",
  name: "",
  age: "",
  residence: "",
  birthplace: "",
  notes: "",
  personalDescription: "",
  ideology: "",
  concept: "",
  clan: "Brujah",
  sire: "",
  nature: "Survivor",
  demeanor: "Stoic",
  generation: "13",
  hunger: 1,
  attributes: {
    Siła: 2,
    Zręczność: 2,
    Wytrzymałość: 2,
    Charyzma: 2,
    Manipulacja: 2,
    Opanowanie: 2,
    Inteligencja: 2,
    Spryt: 2,
    Determinacja: 2,
  },
  abilities: {
    Atletyka: 0,
    Bijatyka: 0,
    Rzemiosło: 0,
    "Prowadzenie pojazdów": 0,
    "Broń palna": 0,
    Kradzież: 0,
    "Broń biała": 0,
    Skradanie: 0,
    "Sztuka przetrwania": 0,
    "Rozumienie zwierząt": 0,
    Etykieta: 0,
    przebiegłość: 0,
    Zastraszanie: 0,
    Przywództwo: 0,
    "Występy publiczne": 0,
    Perswazja: 0,
    Intuicja: 0,
    cwaniactwo: 0,
    "Wiedza akademicka": 0,
    Czujność: 0,
    Finanse: 0,
    Śledztwo: 0,
    Medycyna: 0,
    Okultyzm: 0,
    Polityka: 0,
    Nauka: 0,
    Technologia: 0,
  },
  disciplines: {
    Primary: "przyspieszenie",
    Secondary: "potencja",
    Tertiary: "prezencja",
  },
  disciplinePowers: [
    {
      discipline: "",
      name: "",
      description: "",
    },
  ],
  backgrounds: {
    Allies: 1,
    Contacts: 1,
    Generation: 1,
    Herd: 0,
    Influence: 1,
    Resources: 1,
  },
  virtues: {
    Conscience: 3,
    "Self-Control": 3,
    Courage: 3,
  },
});
